### ISSUE TITLE
How to handle MSI

### ISSUE THREAD

**Issue by patidarr** [oncokb/oncokb-annotator#10]
Hi,

Is it possible to give MSI Status as input to OncoKBPlots.py?

Thanks,
Rajesh

**Comment by zhx828** [comment]
@patidarr I'm so sorry about missed your question for such long time... For MSI-H cases, you just need to specify MSI-H in the protein change column that would work.

**Comment by zhx828** [comment]
Oh I forgot to mention, MSI-H should be specified under MAF file.
