### ISSUE TITLE
PIK3CA E545Q varying classification

### ISSUE THREAD

**Issue by juberpatel** [oncokb/oncokb-annotator#112]
PIK3CA E545Q is given HIGHEST_LEVEL 3B when run with tumor type (-t BREAST) but gets HIGHEST_LEVEL 1 when run without tumor type. I am using HGVSp_Short method.

**Comment by zhx828** [comment]
@juberpatel when a tumor type is not specified, oncokb-annotator give highest level available for the variant. `BREAST` does not exist on OncoTree. If you do -t `Breast Cancer` you will see the the annotation as Level 1

**Comment by juberpatel** [comment]
Thanks, that works. I was going by OncoTree where the code for breast cancer is BREAST.

<img width="321" alt="Screen Shot 2020-11-17 at 12 58 36 AM" src="https://user-images.githubusercontent.com/892500/99352244-47bdc780-2870-11eb-9a88-c727b1784ed3.png">

**Comment by zhx828** [comment]
@juberpatel oh that's not Breast Cancer but rather tissue level Breast.
