### ISSUE TITLE
What is the difference between "Likely Oncogenic" and "Predicted Oncogenic"?

### ISSUE THREAD

**Issue by juberpatel** [oncokb/oncokb-annotator#113]
Oncogenic category "Predicted Oncogenic" is not mentioned in README.md. How is it different from "Likely Oncogenic"?

**Comment by zhx828** [comment]
@juberpatel please see https://sop.oncokb.org/ Chapter 4, I, G. Oncogenic Mutations.

**Comment by juberpatel** [comment]
I don't see any mention of "Predicted Oncogenic" in the SOP.

**Comment by zhx828** [comment]
@juberpatel oh my bad. It's in the 4, I, J Hotspot Mutations.
