### ISSUE TITLE
TCGA samples implementation problem

### ISSUE THREAD

**Issue by anitalu724** [oncokb/oncokb-annotator#114]
Hello, 
I used a MAF file from TCGA to run MafAnnotator and ClinicalDataAnnotation and found a problem that the code in AnnotatorCore.py directly split my original sample id which caused all my results wrong.

**Comment by zhx828** [comment]
@anitalu724 thanks for letting us know. Do you mind sharing your files so we could reproduce the issue?

**Comment by anitalu724** [comment]
@zhx828 Sure. [TCGA MAF samples](https://drive.google.com/file/d/1rSp42Mk6VCVM7GmMTacTDwDCMTkimcIj/view?usp=sharing)
The link file above was the one I used to run MafAnnotator and ClinicalDataAnnotation. The problem seems to be in AnnotatorCore.py where there is a function called **getsampleid**. In that function, my sample id will be split and cause all the results wrong. Thank you so much.

**Comment by zhx828** [comment]
@anitalu724 the issue should be fixed in the master branch. Could you test on your end, and confirm it fixes the issue? Then I can make the release. Thank you!
