### ISSUE TITLE
example data doesn't seem correct

### ISSUE THREAD

**Issue by gsdowns** [oncokb/oncokb-annotator#12]
Hi,

I tried running your example data, and the results (example_maf.onckkb.txt) do not match what I see on the OncoKB website.

For example, the PIK3CA E542K variant was annotated as level 3B and 4, but here:

http://oncokb.org/#/gene/PIK3CA/variant/E542K

...it says 3A. None of the levels in the output match what I see online.

Am I doing something wrong?

thanks for your help,
Greg.
--

**Comment by jjgao** [comment]
Hi Greg:

PIK3CA E542K is level 3A only in breast cancer, so it's level 3B in other cancer types including GBM per our [levels definition](http://oncokb.org/#/levels).

Our OncoKB API could be used to verify the level assignments:

http://oncokb.org/api/v1/search?hugoSymbol=PIK3CA&variant=E542K&tumorType=brca

http://oncokb.org/api/v1/search?hugoSymbol=PIK3CA&variant=E542K&tumorType=gbm

I am investigating the level 4 evidence.

**Comment by gsdowns** [comment]
Hi JianJiong,

That makes sense, thanks for explaining. Is there a way to get all drugs and their levels for a varaint, without knowing the cancer type? In this example, 3A in breast cancer, 3B in all other types? Or is it always required to know the cancer type?

Thanks,
Greg.

**Comment by jjgao** [comment]
All the drugs and levels are shown on each gene page. You can also download from Data Access page. We cannot define all 2B or 3B levels for every cancer type. You can infer them from levels 1, 2A or 3B associations. 

I am going to close this issue, but please feel free to comment.
