### ISSUE TITLE
GET Requests Fail

### ISSUE THREAD

**Issue by HershGupta404** [oncokb/oncokb-annotator#122]
These [lines](https://github.com/oncokb/oncokb-annotator/blob/master/AnnotatorCore.py#L1458-L1471) that trigger if a post request does not work, fail unless all information, including optional fields, are specified for a protein query. This is due to all properties not being instantiated in the  [protein query](https://github.com/oncokb/oncokb-annotator/blob/master/AnnotatorCore.py#L1378-L1390) class.

**Comment by zhx828** [comment]
This issues should be fixed in https://github.com/oncokb/oncokb-annotator/pull/128. Closing this ticket, please let me know if you see have the issues.
