### ISSUE TITLE
support long tsv format for input cnv data

### ISSUE THREAD

**Issue by andurill** [oncokb/oncokb-annotator#123]
Hi,

I know that currently the tool requires input CNA data to be in gistic2.0 format. However, since both the mutations maf and input SV are in the long format (each row with a sample level alteration), it make sense from a user perspective to also support similar long format for input CNA data.

For example:

Gene Symbol|Locus ID|Cytoband|Seg.CN|Tumor_Sample_Barcode
MET|0|0|2|TCGA-05-4417-01
CDKN2A|0|0|-2|TCGA-02-0033-01
...

I understand if this isn't a priority but just wanted to inquire if something like this was considered at all? Thanks.

**Comment by zhx828** [comment]
@andurill thanks for the feedback! It makes sense to me. Is there any standard format I can follow?

**Comment by zhx828** [comment]
@andurill I want to follow up with you on this issue. Could you give me a few pointers?

**Comment by andurill** [comment]
@zhx828 sorry, I missed the github email notifications.

Besides gistic, I am not aware of a standard format for copy number variations. I think allowing a long format instead of wide format as I have suggested in my first comment above will be helpful. I am also slightly modifying the code for my needs to allow accepting IMPACT and Facets CNV outputs. If this is of interest, I can also do a pull request when its ready.

**Comment by zhx828** [comment]
@andurill if it's not much of trouble to standardize your effort, a pr would be appreciated. After looking at your pr, our team can discuss what else format we can support. Thank you!

**Comment by zhx828** [comment]
@andurill sorry about the delay on this feature. When you get a chance, could you take a look whether https://github.com/oncokb/oncokb-annotator/pull/162 works for you?
