### ISSUE TITLE
can get web api version?

### ISSUE THREAD

**Issue by jeongmeani** [oncokb/oncokb-annotator#136]
Hi

using oncokb-annotator, i have been doing cancer annotation.
and i could find out that oncokb web-api is updated regularly, this changes have influence on some result of same sample.

so i want to get api version i used.

is there way to check it?

Best regards

Jeongmin

**Comment by zhx828** [comment]
@jeongmeani could you specify what changes you encountered recently? There were some changes for oncokb-annotator, but not API though.

**Comment by zhx828** [comment]
You can get the data version from https://www.oncokb.org/api/v1/info. And we make software releases regularly which may impact the results. https://github.com/oncokb/oncokb/releases
Let me know what exactly you are looking for, happy to help when I have more info.
