### ISSUE TITLE
Blank results for annotation 

### ISSUE THREAD

**Issue by xiw588** [oncokb/oncokb-annotator#139]
Hi, I tried to run annotation using the following code, but got the False results for all variants. 
python MafAnnotator.py -i "OncoKB_test.txt" -o "test_oncoKB.txt"  -b token 

I am wondering if I did anything wrong

Here I attached the test sample here, and hope you can help me figure this out. 

Thank you.

<img width="992" alt="Screen Shot 2021-10-25 at 12 00 23 AM" src="https://user-images.githubusercontent.com/31411260/138632663-8ca6ac10-3498-4980-84a0-a92098f01fbe.png">

**Comment by zhx828** [comment]
@xiw588 sorry about the late response. Not sure why it fall off my radar. I will take a look.

**Comment by zhx828** [comment]
@xiw588 could you mind send me the file so I can reproduce the issue easily. Thanks in advance.

**Comment by zhx828** [comment]
@xiw588 follow up on this. Are you still seeing the issue? If yes, could you send me a test file to reproduce? Thanks!

**Comment by zhx828** [comment]
Gonna close this ticket since I haven't heard back from the user. Will reopen if situation changes.
