### ISSUE TITLE
Definition of functional fusion?

### ISSUE THREAD

**Issue by pegasusCN** [oncokb/oncokb-annotator#143]
Hi, I really appreciated you guys develop such a tool for variant annotation, it helps me a lot.
As I can see, there is statement about fusion annotation, and this tool only annotate 'functional fusion', I don't know much about fusion, and I have three questions:

1. how you define a 'functional fusion'? I mean, if I have to check whether a fusion I wanna annotated is functional through OncoKB website, there is no necessary using this tool then.
2. how can I get these 'functional' infomation by any other tools or databases? I've read some pages of your OncoKB SOP but I didn't figure it out. 
3. what is the difference if I use OncoKB web API to annotate a variant?

By the way, I saw a 'allAnnotatedVariants.txt' in OncoKB api v1, it contains information that help my question 2, but it has been deprecated since 09/2019, is there any chance that I can get an updated version?

Thanks again!

**Comment by zhx828** [comment]
> * how you define a 'functional fusion'? I mean, if I have to check whether a fusion I wanna annotated is functional through OncoKB website, there is no necessary using this tool then. 

The functional fusion is mostly used with the structural variant especially in the patient report. When a sample is sequenced, we often see a lot of structural variants but not all of them are functional fusions. When you already have a fusion file, meaning they should all be functional.

> * how can I get these 'functional' infomation by any other tools or databases? I've read some pages of your OncoKB SOP but I didn't figure it out.

There is no finite functional fusion list. But you can check some pancan studies(such as https://www.cbioportal.org/study/summary?id=msk_impact_2017) to see what most frequently seen fusions.

> * what is the difference if I use OncoKB web API to annotate a variant?

It's the same, oncokb-annotator uses the API as well.

> By the way, I saw a 'allAnnotatedVariants.txt' in OncoKB api v1, it contains information that help my question 2, but it has been deprecated since 09/2019, is there any chance that I can get an updated version?

We no longer provide such list. We found the list usually leads to inaccurate analysis. If you could let us know your use case, we are happy to provide other tools for your usage.

**Comment by pegasusCN** [comment]
Thanks for reply, it's very helpful.

> We no longer provide such list. We found the list usually leads to inaccurate analysis. If you could let us know your use case, we are happy to provide other tools for your usage.
Well, the thing is I'm tring to build a local annotation database since I've met some situation(network issue and resources mostly) that can't use online annotator, so I want to make it feasible to query a variant and get its biology effect/oncogenicity/evidence level in my local machine.

**Comment by zhx828** [comment]
@pegasusCN which country are you living in? We are planning to do global deployment, will definitely consider your use case when possible. Our API includes nontrivial logics. Even you can have that list of variants, you will not get accurate annotation.

**Comment by pegasusCN** [comment]
> @pegasusCN which country are you living in? We are planning to do global deployment, will definitely consider your use case when possible. Our API includes nontrivial logics. Even you can have that list of variants, you will not get accurate annotation.

China. I got what you mean, hope you guys can do better :)
Thanks again!
