### ISSUE TITLE
Having different annotations from different query type on the same mutation 

### ISSUE THREAD

**Issue by ZWael** [oncokb/oncokb-annotator#148]
Hello, 
I made this bash script for reproducible example:

``
echo -e "Hugo_Symbol Chromosome Start_position End_position Reference_allele Tumor_seq_allele1 Tumor_seq_allele2 HGVSP_Short\nMYD88 3 38182641 38182641 T T C p.L265P" >maf_file.txt
``
``
sed -e "s/ /\t/g" maf_file.txt >maf_file.tsv
``

``
python MafAnnotator.py -i maf_file.tsv    -o output1.tsv    -b apitoken  -r GRCh37 -q HGVSp_Short
``

``
python MafAnnotator.py -i maf_file.tsv    -o output2.tsv    -b apitoken -r GRCh37 -q Genomic_Change
``

First query  -q HGVSp_Short
``
cat output1.tsv | cut -f1,9-11,13
Hugo_Symbol     GENE_IN_ONCOKB  VARIANT_IN_ONCOKB       MUTATION_EFFECT ONCOGENIC
MYD88   True    True    Gain-of-function        Oncogenic
``

Second query -q Genomic_Change
``
cat output2.tsv | cut -f1,9-11,13
Hugo_Symbol     GENE_IN_ONCOKB  VARIANT_IN_ONCOKB       MUTATION_EFFECT ONCOGENIC
MYD88   True    True    Unknown Predicted Oncogenic
``

Note that for the same mutation we have a Gain-of-function and Unknown mutation effect depending in the query type 

as in the web api : 

* Annotate mutation by genomic change :

![image](https://user-images.githubusercontent.com/27080672/147374490-68340ea8-e097-48a8-80e7-525755182453.png)
![image](https://user-images.githubusercontent.com/27080672/147374505-f515b3b6-1157-45db-8301-df1681913cb3.png)

* Annotate mutation by protein change : with the same Hugo and protein change (as the first query result) MYD88 and L265P

![image](https://user-images.githubusercontent.com/27080672/147374522-f89305c9-aefb-49d0-a4f5-b859c59f3a0f.png)

Can the OncoKB team give us some insight ?

**Comment by zhx828** [comment]
This is an interesting one. The genome-nexus annotates the genomic change with stop_lost as consequence. I will look into the issue.
