### ISSUE TITLE
Different results from api when using GET or POST

### ISSUE THREAD

**Issue by pegasusCN** [oncokb/oncokb-annotator#149]
Hi there, I used api to annotate some variants but I found the results were different by different request methods.
For example, when I use 'curl -X GET' to annotate ZFHX3 p.R2740fs*15, its oncogenicity was 'Likely Oncogenic', but if I use 'curl -X POST', it turns to be empty.

**Comment by pegasusCN** [comment]
Same thing even happened in BRAF V600E, GET or POST shows diffrent annotation.
![1](https://user-images.githubusercontent.com/77309046/147534653-1a8b6190-82b4-4735-8e5b-61d964e74e8b.png)
![2](https://user-images.githubusercontent.com/77309046/147534663-21f4ff83-9842-41c9-9972-b1ec34825bba.png)

**Comment by zhx828** [comment]
It seems to be the empty consequence playing a role. Let me fix.
