### ISSUE TITLE
multiple var depend durgs

### ISSUE THREAD

**Issue by summerghw** [oncokb/oncokb-annotator#150]
![image](https://user-images.githubusercontent.com/39901746/147625581-db63e97c-d5fe-4a3d-9972-6f46913202f5.png)
In mycancergenome, there are some durgs depend on multiple varitation。will oncokb-annotator implementation this situation？

**Comment by zhx828** [comment]
@summerghw OncoKB annotates the alteration independently. We do have plan to support interacting alterations, but at this moment, we do not list all required alterations for one treatment. However, we DO indicate resistance mutations in some settings and list therapeutics that are effective in resistance mutations.
