### ISSUE TITLE
none oncogenic mutation was annotated as oncogenic mutation 

### ISSUE THREAD

**Issue by summerghw** [oncokb/oncokb-annotator#159]
Hey.dear developers:
thank you for your contribution.
when i try to annotation a Breast Cancer sample,
`ATM  c.2127T>C c.6006+8T>A c.6975+13dup ` I found these three mutation was annotated as Likely Oncogenic mutation, and has level_3B durgs, but i did not find them in https://www.oncokb.org/gene/ATM#tab=FDA this page. Is that means this is a annotation error or it did not show all the alterations on web site?
Another question is `BRCA2  c.1813del p.I605Yfs*9`  was annotated as Level3A and level_3b, but i think FDA has permit as level A envidence in Breast Cancer. Is that because the database is not update yet or i was misunderstanding.

**Comment by pegasusCN** [comment]
Hi, I'm not a official staff, I saw you were using some 'HGVSc' mutation and tring to find them on OncoKB website, right? but based on the content of OncoKB web site, generally, it's 'Alteration' gives you 'HGVSp' infomation , and sometimes 'Alteration' would be 'Deletion', 'Truncating mutation', etc,. Please refer to OncoKB's SOP[http://sop.oncokb.org/](url) to see the details.
Your second question, as I checked, FDA did approved level 1 drugs with gBRCAm(germline BRCA mutation) in breast [cancer,](https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/208558s023lbl.pdf#page=56) but it seems OncoKB only contains somatic variants for now, so based on clinical info, its annotation shows level 3.

**Comment by summerghw** [comment]
@pegasusCN 
thank you for reply. it helps alot. but i still have some questions.
iIunderstand the answer about BRCA.
Actully i was using oncokb annotator python script(mafannotator.py using -c  clinical.txt -b lisencecode -i VEP.maf -o result.txt ) to annotation. I find these three ATM mutation in my result has level3 durgs, but i did not find them in website. I think there are not oncogenic mutations,not in Alteration 'HGVSp' list or belongt to 'Deletion' or 'Truncationg mutation'.

**Comment by zhx828** [comment]
Gonna close this ticket since I haven't heard back from @summerghw . Will reopen if situation changes.
