### ISSUE TITLE
Alteration content

### ISSUE THREAD

**Issue by pegasusCN** [oncokb/oncokb-annotator#169]
Is there any api or file could provide OncoKB's alterations content? By now it showes 5730 alterations but I wonder what exact alteration in it so that I can remove those markers unavailable in OncoKB to pass unnecessary annotation attempt.

**Comment by zhx828** [comment]
> Is there any api or file could provide OncoKB's alterations content? By now it showes 5730 alterations but I wonder what exact alteration in it so that I can remove those markers unavailable in OncoKB to pass unnecessary annotation attempt.

@pegasusCN We don't provide such endpoint. And we do not suggest filtering the list based on curated alterations. We have categorical variants which will provide annotations for relevant alterations. For instance, DNA binding domain missense mutations(https://www.oncokb.org/gene/TP53/102_292mis), all missense mutations in the range will have annotations.

We are working on an endpoint to provide genome coverage based on OncoKB alterations. It will improve the annotation performance to annotate only the ones that in the coverage. But the coverage could be very broad for some genes.
