### ISSUE TITLE
input to MafAnnotator.py

### ISSUE THREAD

**Issue by vedellpt** [oncokb/oncokb-annotator#18]
Hi, 

I like this program. I am using it to a current project. I have a few questions about MafAnnotator.py. 

1. Should the input MAF should be pre-filtered to include only "functional mutations"? I noticed that your example MAF only has functional mutations.
2. For elements of the MAF that don't have annotated protein positions (e.g. intronic mutations), I seem to be getting the messages of the form "position wrong at lineN -/M" where M and N are integers. Why is this? I looked at the logic in the program. It seems to be checking the HGVSp columns against the Protein_position column which are both unpopulated in the case of mutations that don't cause an amino acid coding change.
3. Should the read depth columns have any effect on the results? 
4. For a specific example related to all of these questions, consider the attached file which contains the output file where the input files only differ in that the columns t_depth (368), t_ref_count (164), t_alt_count (86), n_depth (359), n_ref_count (249) and n_alt_count (1)  have NA in one file and they have integers in parentheses above in the other. Please note the sums don't add up because the allele-specific read counting was capped at 250 in the generating program. 
5. I was not expecting the KIT intronic mutation in the attachment would be actionable, so my sense is that the result with the allele counts populated is correct. But, I would like to verify that this is the desired results. In other words, should this intron KIT mutations be considered to be an actionable mutation?

Thanks,
Pete Vedell
Informatics Specialist
Mayo Clinic
Vedell.Peter@mayo.edu
[example_unexpected_result.maf.transposed.txt](https://github.com/oncokb/oncokb-annotator/files/2368039/example_unexpected_result.maf.transposed.txt)

**Comment by jjgao** [comment]
Hi @vedellpt,

Thanks for contacting us!

1. No, you can include all mutations.
2. Please ignore that warning message. I'll fix it in future.
3. No.
5. The KIT intronic mutation should not be oncogenic or actionable. I'll look into it.

**Comment by jjgao** [comment]
I ran the MafAnnotator for your MAF and neither KIT mutations were annotated as oncogenic or actionable. Would you please pull the latest code and try again?

**Comment by vedellpt** [comment]
OK. Yes, I will pull the latest code and try again. Thanks.

Pete
