### ISSUE TITLE
open() mode 'rU' invalid mode

### ISSUE THREAD

**Issue by gruenbergera** [oncokb/oncokb-annotator#188]
Hello,

It looks like on line 480 of AnnotatorCore.py, open(eventfile, 'rU'), the mode for open() is set as rU.  I believe python 3.11+ no longer has U as one of the valid modes, which causes some run time issues as is (if you're using 3.11 and newer, of course).

> open()](https://docs.python.org/3/library/functions.html#open), [io.open()](https://docs.python.org/3/library/io.html#io.open), [codecs.open()](https://docs.python.org/3/library/codecs.html#codecs.open) and [fileinput.FileInput](https://docs.python.org/3/library/fileinput.html#fileinput.FileInput) no longer accept 'U' (“universal newline”) in the file mode. In Python 3, “universal newline” mode is used by default whenever a file is opened in text mode, and the 'U' flag has been deprecated since Python 3.3. The [newline parameter](https://docs.python.org/3/library/functions.html#open-newline-parameter) to these functions controls how universal newlines work. (Contributed by Victor Stinner in [bpo-37330](https://bugs.python.org/issue?@action=redirect&bpo=37330).)

https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11 

In any case, whether this is a real issue or not, I appreciate the great work your organization contributes to the research community.

**Comment by zhx828** [comment]
Thank you! We will look into.
