### ISSUE TITLE
Automizing MSI/TMB FDA-approved drug recommendation via API

### ISSUE THREAD

**Issue by ibrahimkurt** [oncokb/oncokb-annotator#193]
Hello,

Is there a way to use manual URL/API or oncokb annotator scripts to post MSI-H and TMB-H and automatically get responses regarding the FDA-approved drug recommendations per cancer type?

**Comment by zhx828** [comment]
@ibrahimkurt you can use Atypical Alteration format https://github.com/oncokb/oncokb-annotator#atypical-alteration
