### ISSUE TITLE
Is there an historic of annotaions changes ?

### ISSUE THREAD

**Issue by ZWael** [oncokb/oncokb-annotator#196]
after a rerun of oncokb-annotator.
I remarked a change of annotation from Likely Neutral, to Likely Oncogenic 
Can I date the annotation update ?

**Comment by zhx828** [comment]
@ZWael you should run the `https://github.com/oncokb/oncokb-annotator/blob/master/GenerateReadMe.py` script on every run. It will generate a file including the data version and annotation date.

**Comment by ZWael** [comment]
Thanks @zhx828
