### ISSUE TITLE
MafAnnotator.py run unsuccessfully with error of json decode

### ISSUE THREAD

**Issue by cisplain** [oncokb/oncokb-annotator#20]
I'm a Chinese and normally the unicode is UTF-8.
When I run MafAnnotator.py, the error occurred as follows:

#####################################################################
########################### parting line ################################
annotating data/example_maf.txt...
Traceback (most recent call last):
  File "MafAnnotator.py", line 81, in <module>
    main(sys.argv[1:])
  File "MafAnnotator.py", line 68, in main
    processalterationevents(inputmaffile, outputmaffile, previousresultfile, defaultcancertype, cancertypemap, False)
  File "/Users/peiyuchen/Biosoft/oncokb-annotator-1.0.6/AnnotatorCore.py", line 129, in processalterationevents
    inithotspots()
  File "/Users/peiyuchen/Biosoft/oncokb-annotator-1.0.6/AnnotatorCore.py", line 120, in inithotspots
    missensesinglehotspots = gethotspots(cancerhotspotsbaseurl+"/api/hotspots/single", "single residue")
  File "/Users/peiyuchen/Biosoft/oncokb-annotator-1.0.6/AnnotatorCore.py", line 97, in gethotspots
    hotspotsjson = json.load(urllib.urlopen(url))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 33 column 1 (char 6 - 477818)
#########################################################################

I wonder if it resulted from my Chinese system unicode, so I shifted my mac in English system. However, nothing changed, same error as before.
Just a little python background so I cannot solve this problem by myself, could anyone help me to figure out what's wrong with my MafAnnotator.py?

Thanks a lot for helping me.

**Comment by jjgao** [comment]
@cisplain Thanks for bringing this to my attention. I'll look into it.

**Comment by jjgao** [comment]
@cisplain could you try to pull the latest code and try it out?

**Comment by cisplain** [comment]
> @cisplain could you try to pull the latest code and try it out?

Thank you for your attention. 
I have tried the latest code but it failed as before. 

Here is what I found seems like my problem. But I don't know how to implement...
[https://github.com/rq/rq/issues/996](url)

Hope it can help we figure out. 
Thank you a lot!

**Comment by cisplain** [comment]
> @cisplain could you try to pull the latest code and try it out?

I ran successfully on other mac.
Maybe it is a problem of my mac setting.
I have upgrade my Mac OS before. 
Thank you for your help.

**Comment by jjgao** [comment]
Thanks for the update.

**Comment by kgaonkar6** [comment]
Hello,

Thank you for this tool, I have been able to get results very useful results using python Python 2.7.15 ! However recently , I'm having the same issue as above, MafAnnotator.py runs unsuccessfully gives the json errors and the output maf file has the oncoKB annotation header but no information in the columns. Could it be because of python3 which I installed this week ?  I was getting these errors as well SyntaxError: Missing parentheses in call to 'print'. Did you mean print('for help: python MafAnnotator.py -h')? which I was able to fix by changing the print syntax with parentheses in python3. 

Please let me know if you need more information.

Thanks,
Krutika

**Comment by jjgao** [comment]
@kgaonkar6 thanks for the message. Would you mind sending a pull request of your fix?

**Comment by kgaonkar6** [comment]
Just sent you a pull request with the print command fixes and urllib to urllib.request change which was causing the json errors and now seems to run successfully on python 3 for annotating maf files.

**Comment by zhx828** [comment]
This is fixed in https://github.com/oncokb/oncokb-annotator/pull/41
