### ISSUE TITLE
Oncokb gene symbol/behavior with gene aliases

### ISSUE THREAD

**Issue by pintoa1-mskcc** [oncokb/oncokb-annotator#203]
If I provide a gene symbol which is actually an alias to a known oncokb gene, will oncokb recognize the alias and annotate accordingly? Or would I need to provide the expected oncokb gene name to get the annotation?

**Comment by zhx828** [comment]
> If I provide a gene symbol which is actually an alias to a known oncokb gene, will oncokb recognize the alias and annotate accordingly? Or would I need to provide the expected oncokb gene name to get the annotation?

We recognize gene alias. For instance if you query `BRAF1 V600E` instead of `BRAF V600E`, you will get the same response. Some language in the summaries might need to be updated though, but I don't think it affects the data quality.

**Comment by pintoa1-mskcc** [comment]
This also applies for FusionAnnotator?

**Comment by zhx828** [comment]
> This also applies for FusionAnnotator?

yes

**Comment by pintoa1-mskcc** [comment]
I found a gene in my gtf file "TRAC"[https://www.genecards.org/cgi-bin/carddisp.pl?gene=TRAC&keywords=TRAC] which matches TRA in gene cards and NCBI, however the gene aliases listed on oncokb/cancer_geneList do not include TRAC. Will this mean that my TRAC gene will not be annotated as an oncogene? 

I am seeing that the genes in my gtf file that are not in the aliases of oncokb are primarily the T cell receptor loci (or IGH@, which is not in oncokb, but is a cancer gene) 

Below are the oncokb accepted symbols that my gtf file is lacking a match in either aliases/name
>   "IGH"        "IGK"        "IGL"        "TRA"        "TRB"        "TRD"        "TRG"        "RNF217-AS1"

**Comment by zhx828** [comment]
> I found a gene in my gtf file [TRAC](https://www.genecards.org/cgi-bin/carddisp.pl?gene=TRAC&keywords=TRAC) which matches TRA in gene cards and NCBI, however the gene aliases listed on oncokb/cancer_geneList do not include TRAC. Will this mean that my TRAC gene will not be annotated as an oncogene?
> 
> I am seeing that the genes in my gtf file that are not in the aliases of oncokb are primarily the T cell receptor loci (or IGH@, which is not in oncokb, but is a cancer gene)
> 
> Below are the oncokb accepted symbols that my gtf file is lacking a match in either aliases/name
> 
> > "IGH"        "IGK"        "IGL"        "TRA"        "TRB"        "TRD"        "TRG"        "RNF217-AS1"

Sorry about the late reply.
We consider [TRAC](https://www.genecards.org/cgi-bin/carddisp.pl?gene=TRAC) and [TRA](https://www.genecards.org/cgi-bin/carddisp.pl?gene=TRA) two different genes. In the HGNC gene list which is the one we use, they only associate one symbol with one gene. Therefore TRA is not associated as gene alias of TRAC
