### ISSUE TITLE
Logical to filter VCFs to OncoKB gene list before annotation?

### ISSUE THREAD

**Issue by SpikyClip** [oncokb/oncokb-annotator#211]
I process large VCFs and am looking to annotate them using OncoKB `MafAnnotator.py` in an efficient way. I was wondering if its appropriate to filter VCFs to the [OncoKB gene list](https://www.oncokb.org/cancer-genes) with BCFtools (taking advantage of multithreading speed) then annotating the output with OncoKB.

The main question is whether the gene list above is completely inclusive of all possible annotations produced by `MafAnnotator.py`? The second question is whether this might be redundant if OncoKB is already doing this under the hood.

**Comment by zhx828** [comment]
@SpikyClip sorry about the late reply. No need to filter, OncoKB already doing that.

**Comment by SpikyClip** [comment]
Ended up pre-filtering (because I had a pre-filtering step anyway with other rules) keeping all variants that intersected with a bed file containing all the genes in the oncokb gene list. I don't think(?) I am missing any possible annotations this way.

**Comment by zhx828** [comment]
> Ended up pre-filtering (because I had a pre-filtering step anyway with other rules) keeping all variants that intersected with a bed file containing all the genes in the oncokb gene list. I don't think(?) I am missing any possible annotations this way.

Sure, but make sure for fusion event, check both genes.
