### ISSUE TITLE
update doc to use genome nexus annotator

### ISSUE THREAD

**Issue by jjgao** [oncokb/oncokb-annotator#22]
with msk-override

https://github.com/genome-nexus/genome-nexus-annotation-pipeline

e.g. 

`java -jar annotationPipeline-1.0.0.jar --filename $MAF --output-filename $MAF_GN --isoform-override mskcc --replace-symbol-entrez true`

**Comment by jjgao** [comment]
Let's do https://github.com/genome-nexus/genome-nexus-annotation-pipeline/issues/91 first.

**Comment by zhx828** [comment]
@jjgao any updates on this one?

**Comment by jjgao** [comment]
@zhx828 nop, just pinged @inodb on https://github.com/genome-nexus/genome-nexus-annotation-pipeline/issues/91

**Comment by inodb** [comment]
@jjgao @zhx828 is this issue as a pre step for running the oncokb annotator or moving over from using the oncokb entirely?

We have oncokb annotations in the node cli: https://github.com/genome-nexus/genome-nexus-cli/#include-oncokb-annotations. But not yet in the java cli. Though shouldn't be too complicated to add to the java cli as well
