### ISSUE TITLE
Issues of completing the annotation 

### ISSUE THREAD

**Issue by xiw588** [oncokb/oncokb-annotator#220]
Hi, for some reason the annotation stopped without finishing the whole dataset. Any idea of why this is happening in API? Thanks!

**Comment by zhx828** [comment]
> Hi, for some reason the annotation stopped without finishing the whole dataset. Any idea of why this is happening in API? Thanks!

How big the dataset is and how long did you run the script?

**Comment by xiw588** [comment]
Roughly 90000 rows and it stopped around 3 mins

**Comment by zhx828** [comment]
> Roughly 90000 rows and it stopped around 3 mins

Would retry work? Did you see any exceptions?

**Comment by xiw588** [comment]
Just retried and it failed all the time, but stopped at different rows randomly....

**Comment by xiw588** [comment]
It worked! Thanks

**Comment by xiw588** [comment]
Hi, Same issue occured! My input includes 484249 rows but it stopped at 121015. Any idea of what's happening here? Thanks!
