### ISSUE TITLE
Renew the API Token 

### ISSUE THREAD

**Issue by xiw588** [oncokb/oncokb-annotator#221]
Can you please direct me to the renewal of API Token? Thanks!

**Comment by zhx828** [comment]
> Can you please direct me to the renewal of API Token? Thanks!

If you haven't received an email from us to renew your account, please send us an email. Or you can login here,  https://www.oncokb.org/login, it will provide an option to resend the renewal email.

**Comment by xiw588** [comment]
Problem solved! Thanks
