### ISSUE TITLE
error while using local oncokB url

### ISSUE THREAD

**Issue by patidarr** [oncokb/oncokb-annotator#27]
hi @jjgao,

I want to use a local version of oncokb to make sure the results I am generating today are what I will get down the road on a sample (if I reran a sample). 
I setup the oncokB, and I can browse the site but when I oncokb-annotator I am getting error.
`python /data/MoCha/patidarr/oncokb-annotator-1.1.0/MafAnnotator.py  -i tmp.maf -o tm2.maf -t MEL -u https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev`
```
annotating tmp.maf...
error when processing https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=FANCD2&alteration=X426_splice&tumorType=MEL&consequence=splice_region_variant
error when processing https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=OPA1&alteration=I24V&tumorType=MEL&consequence=missense_variant&proteinStart=24&proteinEnd=24
error when processing https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=SDHA&alteration=L649Efs*4&tumorType=MEL&consequence=frameshift_variant
error when processing https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=BRAF&alteration=V600K&tumorType=MEL&consequence=missense_variant&proteinStart=600&proteinEnd=600
error when processing https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=PPP6C&alteration=T120Nfs*32&tumorType=MEL&consequence=frameshift_variant
done!

```

but when I paste the `https://mocha-cbioportal.ncifcrf.gov/cbioportal-dev/annotate/mutations/byProteinChange?hugoSymbol=BRAF&alteration=V600K&tumorType=MEL&consequence=missense_variant&proteinStart=600&proteinEnd=600` in browser I get following:

`{"query":{"id":null,"type":"regular","hugoSymbol":"BRAF","entrezGeneId":673,"alteration":"V600K","alterationType":null,"svType":null,"tumorType":"MEL","consequence":"missense_variant","proteinStart":600,"proteinEnd":600,"hgvs":null},"geneExist":true,"variantExist":true,"alleleExist":true,"oncogenic":"Oncogenic","mutationEffect":{"knownEffect":"Gain-of-function","description":"","citations":{"pmids":["25417114","20179705","23833300","22535154","26091043","26343582","30630828","23922205","25079552","28783719","19251651","15035987"],"abstracts":[]}},"highestSensitiveLevel":"LEVEL_1","highestResistanceLevel":null,"highestDiagnosticImplicationLevel":null,"highestPrognosticImplicationLevel":null,"otherSignificantSensitiveLevels":[],"otherSignificantResistanceLevels":[],"hotspot":true,"geneSummary":"BRAF, an intracellular kinase, is frequently mutated in melanoma, thyroid and lung cancers among others.","variantSummary":"The BRAF V600K mutation is known to be oncogenic.","tumorTypeSummary":"The RAF-inhibitors encorafenib, dabrafenib and vemurafenib alone or in combination with the MEK-inhibitors binimetinib, trametinib and cobimetinib, respectively, are FDA-approved for the treatment of patients with BRAF V600E/K mutant melanoma.","prognosticSummary":"","diagnosticSummary":"","diagnosticImplications":[],"prognosticImplications":[],"treatments":[{"drugs":[{"ncitCode":"C82386","drugName":"Dabrafenib","uuid":"939cd40b-b515-499d-b099-fd29027c0d17","synonyms":["DABRAFENIB","GSK-2118436","GSK-2118436A","BRAF Inhibitor GSK2118436","Dabrafenib","GSK2118436","Benzenesulfonamide, N-(3-(5-(2-amino-4-pyrimidinyl)-2-(1,1-dimethylethyl)-4-thiazolyl)-2-fluorophenyl)-2,6-difluoro-"]}],"approvedIndications":["Dabrafenib is FDA-approved for BRAF V600E mutant unresectable or metastatic melanoma."],"fdaApproved":null,"level":"LEVEL_1","pmids":["22608338","23051966","22735384"],"abstracts":[]},{"drugs":[{"ncitCode":"C82386","drugName":"Dabrafenib","uuid":"939cd40b-b515-499d-b099-fd29027c0d17","synonyms":["DABRAFENIB","GSK-2118436","GSK-2118436A","BRAF Inhibitor GSK2118436","Dabrafenib","GSK2118436","Benzenesulfonamide, N-(3-(5-(2-amino-4-pyrimidinyl)-2-(1,1-dimethylethyl)-4-thiazolyl)-2-fluorophenyl)-2,6-difluoro-"]},{"ncitCode":"C77908","drugName":"Trametinib","uuid":"fb2bb01c-c0ec-4641-abf7-87f486075022","synonyms":["Mekinist","TRAMETINIB","JTP-74057","MEK Inhibitor GSK1120212","N-(3-{3-cyclopropyl-5-[(2-fluoro-4-iodophenyl)amino]-6,8-dimethyl-2,4,7-trioxo-3,4,6,7-tetrahydropyrido[4,3-d]pyrimidin-1(2H)-yl}phenyl)acetamide","GSK1120212","Trametinib"]}],"approvedIndications":["Dabrafenib + Trametinib is FDA-approved for BRAF V600E or V600K mutant unresectable or metastatic melanoma"],"fdaApproved":null,"level":"LEVEL_1","pmids":["28891408","25265492","25287827","29361468","28991513","23020132","25399551"],"abstracts":[]},{"drugs":[{"ncitCode":"C98283","drugName":"Encorafenib","uuid":"001e534f-3e63-432f-90a6-d1af1759e4e2","synonyms":["LGX-818","Encorafenib","LGX818","LGX 818","ENCORAFENIB","Braftovi"]},{"ncitCode":"C84865","drugName":"Binimetinib","uuid":"feb9f4a3-e374-4c75-8a3b-0f1fbcdbf677","synonyms":["ARRY-438162","Mektovi","Binimetinib","ARRY-162","MEK162","BINIMETINIB"]}],"approvedIndications":["In combination for patients with unresectable or metastatic melanoma with a BRAF V600E or V600K mutation"],"fdaApproved":null,"level":"LEVEL_1","pmids":["29573941"],"abstracts":[]},{"drugs":[{"ncitCode":"C77908","drugName":"Trametinib","uuid":"fb2bb01c-c0ec-4641-abf7-87f486075022","synonyms":["Mekinist","TRAMETINIB","JTP-74057","MEK Inhibitor GSK1120212","N-(3-{3-cyclopropyl-5-[(2-fluoro-4-iodophenyl)amino]-6,8-dimethyl-2,4,7-trioxo-3,4,6,7-tetrahydropyrido[4,3-d]pyrimidin-1(2H)-yl}phenyl)acetamide","GSK1120212","Trametinib"]}],"approvedIndications":["Trametinib is FDA-approved for BRAF V600E or V600K mutant unresectable or metastatic melanoma"],"fdaApproved":null,"level":"LEVEL_1","pmids":["29361468","25399551","22663011","25265492"],"abstracts":[]},{"drugs":[{"ncitCode":"C64768","drugName":"Vemurafenib","uuid":"4e91da20-6cf0-4e07-995f-7f7db4c7c077","synonyms":["Vemurafenib","BRAF(V600E) Kinase Inhibitor RO5185426","RO 5185426","PLX4032","PLX-4032","1-propanesulfonamide, n-(3-((5-(4-chlorophenyl)-1h-pyrrolo(2,3-b)pyridin-3-yl)carbonyl)-2,4-difluorophenyl)-","RG 7204","Zelboraf","BRAF (V600E) kinase inhibitor RO5185426","RG7204","VEMURAFENIB"]}],"approvedIndications":["Vemurafenib is FDA-approved for BRAF V600E mutant unresectable or metastatic melanoma"],"fdaApproved":null,"level":"LEVEL_1","pmids":["28961848","24508103","25399551"],"abstracts":[]},{"drugs":[{"ncitCode":"C64768","drugName":"Vemurafenib","uuid":"4e91da20-6cf0-4e07-995f-7f7db4c7c077","synonyms":["Vemurafenib","BRAF(V600E) Kinase Inhibitor RO5185426","RO 5185426","PLX4032","PLX-4032","1-propanesulfonamide, n-(3-((5-(4-chlorophenyl)-1h-pyrrolo(2,3-b)pyridin-3-yl)carbonyl)-2,4-difluorophenyl)-","RG 7204","Zelboraf","BRAF (V600E) kinase inhibitor RO5185426","RG7204","VEMURAFENIB"]},{"ncitCode":"C68923","drugName":"Cobimetinib","uuid":"eb357145-3b18-4aca-b75a-5e18dd2bf4f9","synonyms":["Cotellic","Cobimetinib","XL518","COBIMETINIB","GDC-0973","MEK Inhibitor GDC-0973"]}],"approvedIndications":["Cobimetinib is FDA-approved for the treatment of patients with unresectable or metastatic melanoma with a BRAF V600E or V600K mutation, in combination with vemurafenib. Cobimetinib is not indicated for treatment of patients with wild-type BRAF melanoma."],"fdaApproved":null,"level":"LEVEL_1","pmids":["27480103","25265494"],"abstracts":[]},{"drugs":[{"ncitCode":"C82386","drugName":"Dabrafenib","uuid":"939cd40b-b515-499d-b099-fd29027c0d17","synonyms":["DABRAFENIB","GSK-2118436","GSK-2118436A","BRAF Inhibitor GSK2118436","Dabrafenib","GSK2118436","Benzenesulfonamide, N-(3-(5-(2-amino-4-pyrimidinyl)-2-(1,1-dimethylethyl)-4-thiazolyl)-2-fluorophenyl)-2,6-difluoro-"]},{"ncitCode":"C1857","drugName":"Panitumumab","uuid":"d7b1d12a-e942-4801-bb64-916c9bdfaaf3","synonyms":["ABX-EGF, Clone E7.6.3","PANITUMUMAB","Vectibix","Panitumumab","MoAb ABX-EGF","ABX-EGF","ABX-EGF Monoclonal Antibody","Monoclonal Antibody ABX-EGF","panitumumab"]},{"ncitCode":"C77908","drugName":"Trametinib","uuid":"fb2bb01c-c0ec-4641-abf7-87f486075022","synonyms":["Mekinist","TRAMETINIB","JTP-74057","MEK Inhibitor GSK1120212","N-(3-{3-cyclopropyl-5-[(2-fluoro-4-iodophenyl)amino]-6,8-dimethyl-2,4,7-trioxo-3,4,6,7-tetrahydropyrido[4,3-d]pyrimidin-1(2H)-yl}phenyl)acetamide","GSK1120212","Trametinib"]}],"approvedIndications":[],"fdaApproved":null,"level":"LEVEL_2B","pmids":["29431699"],"abstracts":[{"link":"http://ascopubs.org/doi/abs/10.1200/JCO.2018.36.4_suppl.627","abstract":"Cutsem et al. Abstract# 627, ASCO 2018"},{"link":"https://academic.oup.com/annonc/article/29/suppl_5/mdy149.026/5039436","abstract":"Cutsem et al. Abstract# O-027, ESMO 2018"}]},{"drugs":[{"ncitCode":"C98283","drugName":"Encorafenib","uuid":"001e534f-3e63-432f-90a6-d1af1759e4e2","synonyms":["LGX-818","Encorafenib","LGX818","LGX 818","ENCORAFENIB","Braftovi"]},{"ncitCode":"C1723","drugName":"Cetuximab","uuid":"5fce3074-e420-4c36-9603-2423daf20118","synonyms":["CETUXIMAB","Cetuximab Biosimilar CMAB009","IMC-C225","Chimeric Anti-EGFR Monoclonal Antibody","Cetuximab Biosimilar KL 140","Cetuximab Biosimilar CDP-1","cetuximab","Chimeric Monoclonal Antibody C225","Cetuximab","Chimeric MoAb C225","Erbitux"]},{"ncitCode":"C84865","drugName":"Binimetinib","uuid":"feb9f4a3-e374-4c75-8a3b-0f1fbcdbf677","synonyms":["ARRY-438162","Mektovi","Binimetinib","ARRY-162","MEK162","BINIMETINIB"]}],"approvedIndications":[],"fdaApproved":null,"level":"LEVEL_2B","pmids":["29431699"],"abstracts":[{"link":"http://ascopubs.org/doi/abs/10.1200/JCO.2018.36.4_suppl.627","abstract":"Cutsem et al. Abstract# 627, ASCO 2018"},{"link":"https://academic.oup.com/annonc/article/29/suppl_5/mdy149.026/5039436","abstract":"Cutsem et al. Abstract# O-027, ESMO 2018"}]}],"dataVersion":"","lastUpdate":"06/19/2019","vus":false}`

Could you please let me know what I am doing wrong here?

Thanks,
@patidarr

**Comment by jjgao** [comment]
@patidarr would you please pull the latest code and give it a try?
