### ISSUE TITLE
Issue with ClinicalDataAnnotator.py, with LEVEL_R2

### ISSUE THREAD

**Issue by patidarr** [oncokb/oncokb-annotator#29]
```
$ python /data/MoCha/patidarr/oncokb-annotator-1.1.0/ClinicalDataAnnotator.py -i 283228/20170910/oncoKB/283228.clinical.txt -o 283228/20170910/oncoKB/283228.oncoKB.clinical.txt -a 283228/20170910/oncoKB/283228.maf,283228/20170910/oncoKB/283228.cnv
annotating 283228/20170910/oncoKB/283228.clinical.txt...
Traceback (most recent call last):
  File "/data/MoCha/patidarr/oncokb-annotator-1.1.0/ClinicalDataAnnotator.py", line 53, in <module>
    main(sys.argv[1:])
  File "/data/MoCha/patidarr/oncokb-annotator-1.1.0/ClinicalDataAnnotator.py", line 40, in main
    processclinicaldata(annotatedalterationfiles, inputclinicalfile, outputclinicalfile)
  File "/gpfs/gsfs6/users/MoCha/patidarr/oncokb-annotator-1.1.0/AnnotatorCore.py", line 495, in processclinicaldata
    il = headers[l]
KeyError: 'LEVEL_R2'
```

but when I ran the same command but version oncokb-annotator-1.0.3, it worked...

**Comment by zhx828** [comment]
@patidarr seems like the annotated MAF file does not have LEVEL_R2 header. You probably need to do some debugging if possible.

**Comment by zhx828** [comment]
And I think the reason it works in 1.0.3 is because in version 1.0.6, we added R2,R3 support. The MAF file needs to be re-annotated with the latest code.

**Comment by patidarr** [comment]
Hi @zhx828, I did generate the maf file using the same version(1.1.0) and it does have following columns.
`mutation_effect oncogenic       LEVEL_1 LEVEL_2A        LEVEL_2B        LEVEL_3A        LEVEL_3B        LEVEL_4 LEVEL_R1        LEVEL_R2        LEVEL_R3        Highest_level   citations`

somehow with these columns the version 1.1.0 ClinicalDataAnnotator.py did not work but 1.0.3 ClinicalDataAnnotator.py worked.

**Comment by zhx828** [comment]
@patidarr do you think you can share the file with us for debugging purpose?

**Comment by patidarr** [comment]
Hi @zhx828,

Please see the attached files.
[128128.clinical.txt](https://github.com/oncokb/oncokb-annotator/files/3350866/128128.clinical.txt)

**Comment by zhx828** [comment]
@patidarr I do need all files in your command including the maf and cnv in order to reproduce the issue.

**Comment by patidarr** [comment]
[128128.maf.txt](https://github.com/oncokb/oncokb-annotator/files/3350892/128128.maf.txt)
[128128.cnv.txt](https://github.com/oncokb/oncokb-annotator/files/3350893/128128.cnv.txt)
Here

**Comment by patidarr** [comment]
Hi @zhx828,
are you able to reproduce the error?

Thanks!!

**Comment by zhx828** [comment]
@patidarr I don't have time at the moment, will take a look later of the day or sometime tomorrow.

**Comment by zhx828** [comment]
@patidarr it works fine for me. I'm on Python 2.7.16. Could you do some debugging?

**Comment by patidarr** [comment]
Hi @zhx828, Thanks for checking it. I am on python 2.7.15. Not sure what debugging I need to do.

**Comment by zhx828** [comment]
Base on your error message, seems like `headers` does not have LEVEL_R2 included, probably that could be a starting point. Try to print out what are in headers and trace back why LEVEL_R2 is not in the list if that's the reason.
