### ISSUE TITLE
Gene symbols

### ISSUE THREAD

**Issue by kpjonsson** [oncokb/oncokb-annotator#32]
Hi guys,

What is the source of the gene symbols you use? 

I'm using `http://oncokb.org/api/v1/genes` to pull down genes and subset on tumor-suppressor genes. This is one of the entries:
```json
{
    "entrezGeneId":84142,
    "hugoSymbol":"FAM175A",
    "name":"family with sequence similarity 175 member A",
    "oncogene":false,
    "curatedIsoform":"ENST00000321945",
    "curatedRefSeq":"NM_139076.2",
    "geneAliases":["ABRA1","CCDC98"],
    "tsg":true
}
```
The "official" symbol for this gene, however, seems to be _ABRAXAS1_: https://www.ncbi.nlm.nih.gov/gene/84142. That is also the primary symbol associated with the gene in the internal instance of the IMPACT series.

**Comment by zhx828** [comment]
@kpjonsson we are trying to inline with MSK portal which inlines with IMPACT. This seems to be outdated in oncokb, I should be able to fix it in the next release.

**Comment by kpjonsson** [comment]
Thanks @zhx828.

FYI, these are all cases I found and the official gene symbol from https://ncbi.nlm.nih.gov/gene:

hugoSymbol | geneAliases | official
--- | --- | ---
FAM175A | ABRA1, CCDC98 | ABRAXAS1
FAM58A | STAR | CCNQ
MRE11A | MRE11, HNGS1, ATLD, MRE11B | MRE11
PARK2 | PRKN, PDJ, LPRS2, AR-JP | PRKN
FAM46C | | TENT5C

Two have the right symbol among the aliases, as you can see.

**Comment by zhx828** [comment]
I don't think we are going to change hugo symbpl at the moment, but the official symbol will be included as alias.
