### ISSUE TITLE
Some MSK Archer fusion annotations are inconsistent with cBioPortal

### ISSUE THREAD

**Issue by sas1531** [oncokb/oncokb-annotator#47]
Hi,
I ran oncokb-annotator on 04/03/2020 on a subset of the MSK IMPACT cohort and some of the archer fusion annotations are inconsistent with cBioPortal. For example the oncogenic column for ` P-0022485-T01-IM6	NR4A3-EWSR1 fusion - Archer ` was blank when I ran the annotator, but on the portal it shows this fusion as likely oncogenic.` P-0024067-T01-IM6	FLI1-EWSR1 fusion - Archer` is another example of this, the annotator result is blank but it's level 4 on the portal. No errors showed up when running FusionAnnotator.py and I cloned the repo right before running it. Attached is a list of the IMPACT samples with the discrepancy in my cohort and the output of the oncogenic column from the annotator. Adjacent is the annotation from the portal that I manually curated. Do you know what could be causing the discrepancy? I'd really appreciate any help. 
Thanks!

**Comment by zhx828** [comment]
@sas1531 it's the fusion name issue. `...  - Archer` is not supported by the annotator, but in the portal we know the gene partners so we would be able to annotate that. You have to do a clean up when annotating the archer cases.

**Comment by sas1531** [comment]
@zhx828 Thanks for the quick response. I'll clean the names and rerun. There are cases where the annotator did correctly annotate the archer fusion: i.e. `SUZ12-JAZF1 fusion - Archer` and `NTRK1-PEAR1 fusion - Archer` are called likely oncogenic by the annotator, which is consistent with the portal. Is there a reason why only some of the archer names are causing issues and not others?

**Comment by zhx828** [comment]
@sas1531 possibly because of the mutation type. It's quite complicated, there might be multiple reasons resolved to that result. Without looking at the original data, I cannot give you a firm answer. But by cleaning up the fusion name, that should work.

**Comment by jjgao** [comment]
@zhx828 maybe we can strip out " - Archer" in our code? Alternatively, if we would like to make it general, we could make it an option for the user to supply the suffix for fusion events https://github.com/oncokb/oncokb-annotator/blob/master/AnnotatorCore.py#L324.

**Comment by zhx828** [comment]
@jjgao wouldn't it too specific to have that for MSK purpose?

**Comment by sas1531** [comment]
@zhx828 I stripped `- Archer` then re-ran the annotator, all of the discrepancies were corrected. Thanks!

**Comment by jjgao** [comment]
@zhx828 I think it's important to fix this b/c the majority of the users of this tool are MSK users who are analyzing the MSK IMPACT study. We should make it as easy as possible for them even if we need to introduce specific code.

One option to make it less specific is to allow the user to specify the regex to extract the two genes? 

e.g. `python FusionAnnotator.py -i $IF -o $OF -c $IC -b $TOKEN -r $REGEX_FUSION`

By default, it could be `([A-Z0-9]+)-([A-Z0-9]+) fusion.*` which will capture both `fusion` and `fusion - Archer`.
