### ISSUE TITLE
Overflow error in AnnotatorCore.py

### ISSUE THREAD

**Issue by myourshaw** [oncokb/oncokb-annotator#50]
This line, when executed on Windows (including 64-bit Windows) fails
```
csv.field_size_limit(sys.maxsize) # for reading large files
```
The error is
```
OverflowError: Python int too large to convert to C long
```
caused by the Windows C long being 32 bits.
The following fixes this, and should be OK for Python 3 and Python 2, on any CPU / OS.
```
import ctypes as ct
csv.field_size_limit(int(ct.c_ulong(-1).value // 2))
```
See [_csv.Error: field larger than field limit (131072)](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072)

**Comment by jjgao** [comment]
Thanks, @myourshaw! Would you please send us a pull request?

**Comment by zhx828** [comment]
@myourshaw want to follow up on this. I don't have any windows system to test. Do you mind send a pr?
