### ISSUE TITLE
Why 'Loss' and 'Gain' CNAs are removed from AnnotatorCore?

### ISSUE THREAD

**Issue by fraterenz** [oncokb/oncokb-annotator#51]
Hi,

I have a basic question. 

Why only 'Amplified' or 'Deleted' CNAs are [processed by AnnotatorCore.py](https://github.com/oncokb/oncokb-annotator/blob/master/AnnotatorCore.py#L401), i.e. why CNAs showing 'Loss' or 'Gain' are filtered out?

Thanks,

Francesco

**Comment by jjgao** [comment]
Hi @fraterenz, Copy number gain and loss in our definition are usually arm-level events that hit hundreds to genes. Since we are annotating per gene, many of these copy number changes per gene are just passenger events.

With that said, we will provide an option to turn on annotation for loss and gain (off by default.

**Comment by fraterenz** [comment]
I see, thank you!

**Comment by fraterenz** [comment]
makes sense, thank you!

**Comment by zhx828** [comment]
@jjgao should this fixed on gene level of arm level? We are going to have CNA on the arm level soon. We should make plan for these two.

**Comment by jjgao** [comment]
@zhx828 good point, let's worry about gene-level for now and see how we can deal with arm-level data later?

I think arm-level data will be in a separate file, so as long as we provide the option, we should be able to allow user to do annotate them with different options.

**Comment by zhx828** [comment]
@fraterenz if you want to include Gain/Loss, you can now include `-z` in your script for the CnaAnnotator.

**Comment by fraterenz** [comment]
Great, thanks! 

From your experience @jjgao and @zhx828, do you think the flag `-z` will include too many false positive/passenger mutations?

**Comment by jjgao** [comment]
@fraterenz that's possible since Gain and Loss from GISTIC results include many arm-level events (which may contain hundred of genes per event).
