### ISSUE TITLE
Errors for example dataset and command 

### ISSUE THREAD

**Issue by likelet** [oncokb/oncokb-annotator#59]
with the latest version of annotator,  I got the following errors with example code.  My token is not Expired (174 days left)
```
ERROR:AnnotatorCore:error when processing https://www.oncokb.org/api/v1/utils/allCuratedGenes.json 
reason: Forbidden
INFO:MafAnnotator:annotating data/example_maf.txt ...
INFO:MafAnnotator:done!
```
any suggestions?
Thanks

**Comment by zhx828** [comment]
@likelet this is after passing the API token?

**Comment by zhx828** [comment]
Sorry, just saw your token is not expired. Let me take a look.

**Comment by zhx828** [comment]
@likelet sorry for the issue. We just made a fix to the annotation service. This should be fixed now. Please let me know if you see any other issues.

**Comment by likelet** [comment]
@zhx828 Thanks for your help, now it works .
